export const words = [
  "Art",
  "Creative",
  "Idea",
  "Art",
  "Creative",
  "Idea",
  "Art",
  "Creative",
];

export const counterItems = [
  { value: 10000, suffix: "+", label: "Digital Artworks Listed" },
  { value: 5000, suffix: "+", label: "Active Collectors" },
  { value: 100, suffix: "+", label: "Featured Artists" },
  { value: 1.5, suffix: "M+", label: "Total Volume Traded" },
];

export const nfts = [
  {
    id: 1,
    title: "Monkey YOLO",
    artist: "CryptoArtist1",
    imageUrl: "monkey1.jpg",
    floorPrice: 0.25,
    totalVolume: 2.8,
    category: "collections",
  },
  {
    id: 2,
    title: "Monkey Hype Smile",
    artist: "NFTMaster",
    imageUrl: "monkey2.jpg",
    floorPrice: 1.2,
    totalVolume: 15.6,
    category: "collections",
  },
  {
    id: 3,
    title: "Monkey Astronaut",
    artist: "RoboPainter",
    imageUrl: "monkey3.jpg",
    floorPrice: 0.89,
    totalVolume: 8.3,
    category: "collections",
  },
  {
    id: 4,
    title: "Dream a lot",
    artist: "FloraChain",
    imageUrl: "nft1.jpg",
    floorPrice: 0.45,
    totalVolume: 3.1,
    category: "art",
  },
  {
    id: 5,
    title: "Best Coin",
    artist: "CyberCreator",
    imageUrl: "nft2.jpg",
    floorPrice: 2.1,
    totalVolume: 22.4,
    category: "art",
  },
  {
    id: 6,
    title: "Digital World 1",
    artist: "RetroDesigner",
    imageUrl: "animation1.jpg",
    floorPrice: 0.33,
    totalVolume: 5.7,
    category: "gaming",
  },
  {
    id: 7,
    title: "Digital World 2",
    artist: "RetroDesigner",
    imageUrl: "animation2.jpg",
    floorPrice: 0.12,
    totalVolume: 4.1,
    category: "gaming",
  },
  {
    id: 8,
    title: "Robotic Cool",
    artist: "ModernDesigner",
    imageUrl: "animation3.jpg",
    floorPrice: 0.19,
    totalVolume: 3.7,
    category: "gaming",
  },
  {
    id: 9,
    title: "Little Panda",
    artist: "AnimaChain",
    imageUrl: "animation4.jpg",
    floorPrice: 0.42,
    totalVolume: 8.4,
    category: "collections",
  },
  {
    id: 10,
    title: "What a Proportion",
    artist: "Geometric Dreams",
    imageUrl: "nft3.jpg",
    floorPrice: 0.85,
    totalVolume: 12.6,
    category: "art",
  },
  {
    id: 11,
    title: "Pinky Monster",
    artist: "GameCraft Studio",
    imageUrl: "nft4.jpg",
    floorPrice: 0.32,
    totalVolume: 28.9,
    category: "gaming",
  },
  {
    id: 12,
    title: "Hello Buddy",
    artist: "Mascot Factory",
    imageUrl: "nft5.jpg",
    floorPrice: 0.45,
    totalVolume: 15.2,
    category: "collections",
  },
  {
    id: 13,
    title: "Beautyful Lady",
    artist: "DigitalArt Masters",
    imageUrl: "nft6.jpg",
    floorPrice: 1.25,
    totalVolume: 42.7,
    category: "art",
  },
  {
    id: 14,
    title: "One Eyed Gamers",
    artist: "CyberPunk Creators",
    imageUrl: "nft7.jpg",
    floorPrice: 0.68,
    totalVolume: 33.4,
    category: "gaming",
  },
  {
    id: 15,
    title: "Cartoon Fox",
    artist: "Animasia Team",
    imageUrl: "nft8.jpg",
    floorPrice: 0.29,
    totalVolume: 19.8,
    category: "collections",
  },
  {
    id: 16,
    title: "Lego Mask",
    artist: "BlockBuilders",
    imageUrl: "nft9.jpg",
    floorPrice: 0.55,
    totalVolume: 25.1,
    category: "collections",
  },
  {
    id: 17,
    title: "Zombie with a Mask",
    artist: "Apocalypse Arts",
    imageUrl: "nft10.jpg",
    floorPrice: 0.39,
    totalVolume: 17.3,
    category: "gaming",
  },
  {
    id: 18,
    title: "What an Egg?",
    artist: "Quirky Collectibles",
    imageUrl: "nft11.jpg",
    floorPrice: 0.18,
    totalVolume: 9.7,
    category: "collections",
  },
  {
    id: 19,
    title: "A Little Pot",
    artist: "Claymation Studio",
    imageUrl: "nft12.jpg", // Diperbaiki typo ekstensi file
    floorPrice: 0.72,
    totalVolume: 14.5,
    category: "art",
  },
  {
    id: 20,
    title: "Cute Monster",
    artist: "Plushie Makers",
    imageUrl: "nft13.jpg",
    floorPrice: 0.23,
    totalVolume: 21.9,
    category: "collections",
  },
  {
    id: 21,
    title: "Sadegg",
    artist: "Meme Factory",
    imageUrl: "nft14.jpg",
    floorPrice: 0.95,
    totalVolume: 38.2,
    category: "collections",
  },
  {
    id: 22,
    title: "Peek a Boo",
    artist: "ToyBox Creatives",
    imageUrl: "nft15.jpg",
    floorPrice: 0.41,
    totalVolume: 27.6,
    category: "collections",
  },
];
